# Generated by Django 3.1.3 on 2021-05-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_full', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('cname', models.CharField(blank=True, max_length=16, null=True)),
                ('lower_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'continents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('continent_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('full_cname', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('city_id', models.SmallIntegerField()),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
                ('lower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_full', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code_full', models.CharField(blank=True, max_length=255, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
    ]
