# Generated by Django 3.1.3 on 2021-05-01 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='continents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={},
        ),
    ]
