# Generated by Django 3.1.3 on 2021-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0003_auto_20210501_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='continents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'managed': False},
        ),
    ]
